name: Integration tests

on:
  push:
    branches:
      - main

jobs:
  build-lambda:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Maven package
        run: |
          cd devoxx-lambda-processor
          mvn install
      - uses: actions/upload-artifact@v4
        with:
          name: devoxxlambda
          path: ./devoxx-lambda-processor/target/devoxxlambda-1.0.0.jar
          retention-days: 20

  build-infrastructure-and-run-tests:
    runs-on: ubuntu-22.04
    needs: build-lambda
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - uses: docker/setup-docker-action@v4
      - uses: actions/download-artifact@v5
        with:
          name: devoxxlambda
          path: ./infrastracture/
      - name: Maven package
        env:
          LAMBDA_PATH: devoxxlambda-1.0.0.jar
          SYSTEM_TEST: true
        run: |
          sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
          sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
          sudo systemctl restart docker
          cd infrastracture
          mvn install
  
#  cdk-deploy:
#    runs-on: ubuntu-22.04
#    needs: build-infrastructure-and-run-tests
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v5
#        with:
#          distribution: 'corretto'
#          java-version: '21'
#      - uses: actions/setup-node@v6
#        with:
#          node-version: '24'
#      - name: Install AWS-CDK
#        run: |
#          npm install -g aws-cdk
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: "eu-west-1"
#      - uses: actions/download-artifact@v5
#        with:
#          name: devoxxlambda
#          path: ./infrastracture/
#      - name: Build infrastructure project
#        run: |
#          cd infrastracture
#          mvn clean install -DskipTests
#      - name: CDK bootstrap
#        env:
#          LAMBDA_PATH: devoxxlambda-1.0.0.jar
#        run: |
#          cd infrastracture
#          cdk bootstrap aws://${{vars.ACCOUNT_ID}}/eu-west-1
#      - name: CDK deploy
#        env:
#          LAMBDA_PATH: devoxxlambda-1.0.0.jar
#        run: |
#          cd infrastracture
#          cdk deploy --require-approval never